package com.gliwka.hyperscan.wrapper;

import com.gliwka.hyperscan.jni.HyperscanNativeLoader;
import com.gliwka.hyperscan.jni.hyperscan;

import java.util.function.IntSupplier;

/**
 * Flags influencing the matching behaviour of the scanner for a particular Expression
 */
public enum ExpressionFlag implements BitFlag {

    /**
     * Expression will be compiled with no flags.
     */
    NO_FLAG(0),

    /**
     * Matching will be performed case-insensitively.
     */
    CASELESS(nativeFlag(hyperscan::HS_FLAG_CASELESS)),

    /**
     * Matching a . will not exclude newlines.
     */
    DOTALL(nativeFlag(hyperscan::HS_FLAG_DOTALL)),

    /**
     * ^ and $ anchors match any newlines in data.
     */
    MULTILINE(nativeFlag(hyperscan::HS_FLAG_MULTILINE)),

    /**
     * Only one match will be generated by the expression per stream.
     */
    SINGLEMATCH(nativeFlag(hyperscan::HS_FLAG_SINGLEMATCH)),

    /**
     * Allow expressions which can match against an empty string, such as .*.
     */
    ALLOWEMPTY(nativeFlag(hyperscan::HS_FLAG_ALLOWEMPTY)),

    /**
     * Treat this pattern as a sequence of UTF-8 characters.
     */
    UTF8(nativeFlag(hyperscan::HS_FLAG_UTF8)),

    /**
     * Use Unicode properties for character classes.
     */
    UCP(nativeFlag(hyperscan::HS_FLAG_UCP)),

    /**
     * compile pattern in prefiltering mode.
     */
    PREFILTER(nativeFlag(hyperscan::HS_FLAG_PREFILTER)),

    /**
     * Report the leftmost start of match offset when a match is found.
     */
    SOM_LEFTMOST(nativeFlag(hyperscan::HS_FLAG_SOM_LEFTMOST)),

    /**
     * Parse the expression in logical combination syntax.
     */
    COMBINATION(nativeFlag(hyperscan::HS_FLAG_COMBINATION)),

    /**
     * Ignore match reporting for this expression. Used for the sub-expressions in logical combinations.
     */
    QUIET(nativeFlag(hyperscan::HS_FLAG_QUIET));

    private final int bits;

    ExpressionFlag(int bitPosition) {
        this.bits = bitPosition;
    }

    /**
     * Get the significant bits for the flag
     * @return int containing the significant bit for the flag
     */
    public int getBits() {
        return bits;
    }

    private static int nativeFlag(IntSupplier supplier) {
        HyperscanNativeLoader.load();
        return supplier.getAsInt();
    }
}
