package com.xenoamess.hyperscan_panama.wrapper;

import com.xenoamess.hyperscan_panama.jni.HyperscanJni;
import com.xenoamess.hyperscan_panama.jni.HyperscanNativeLoader;

/**
 * Flags influencing the matching behaviour of the scanner for a particular Expression
 */
public enum ExpressionFlag implements BitFlag {

    /**
     * Expression will be compiled with no flags.
     */
    NO_FLAG(0),

    /**
     * Matching will be performed case-insensitively.
     */
    CASELESS(FlagBits.VALUES[1]),

    /**
     * Matching a . will not exclude newlines.
     */
    DOTALL(FlagBits.VALUES[2]),

    /**
     * ^ and $ anchors match any newlines in data.
     */
    MULTILINE(FlagBits.VALUES[3]),

    /**
     * Only one match will be generated by the expression per stream.
     */
    SINGLEMATCH(FlagBits.VALUES[4]),

    /**
     * Allow expressions which can match against an empty string, such as .*.
     */
    ALLOWEMPTY(FlagBits.VALUES[5]),

    /**
     * Treat this pattern as a sequence of UTF-8 characters.
     */
    UTF8(FlagBits.VALUES[6]),

    /**
     * Use Unicode properties for character classes.
     */
    UCP(FlagBits.VALUES[7]),

    /**
     * compile pattern in prefiltering mode.
     */
    PREFILTER(FlagBits.VALUES[8]),

    /**
     * Report the leftmost start of match offset when a match is found.
     */
    SOM_LEFTMOST(FlagBits.VALUES[9]),

    /**
     * Parse the expression in logical combination syntax.
     */
    COMBINATION(FlagBits.VALUES[10]),

    /**
     * Ignore match reporting for this expression. Used for the sub-expressions in logical combinations.
     */
    QUIET(FlagBits.VALUES[11]);

    private final int bits;

    ExpressionFlag(int bitPosition) {
        this.bits = bitPosition;
    }

    /**
     * Get the significant bits for the flag
     * @return int containing the significant bit for the flag
     */
    public int getBits() {
        return bits;
    }

    private static final class FlagBits {
        static final int[] VALUES = init();

        private static int[] init() {
            HyperscanJni jni = HyperscanNativeLoader.loadJni();
            return new int[] {
                    0,
                    jni.hsFlagCaseless(),
                    jni.hsFlagDotall(),
                    jni.hsFlagMultiline(),
                    jni.hsFlagSinglematch(),
                    jni.hsFlagAllowempty(),
                    jni.hsFlagUtf8(),
                    jni.hsFlagUcp(),
                    jni.hsFlagPrefilter(),
                    jni.hsFlagSomLeftmost(),
                    jni.hsFlagCombination(),
                    jni.hsFlagQuiet()
            };
        }
    }
}
