package com.xenoamess.hyperscan_panama.wrapper;

import com.xenoamess.hyperscan_panama.jni.HyperscanNativeLoader;

import java.util.function.IntSupplier;

/**
 * Flags influencing the matching behaviour of the scanner for a particular Expression
 */
public enum ExpressionFlag implements BitFlag {

    /**
     * Expression will be compiled with no flags.
     */
    NO_FLAG(0),

    /**
     * Matching will be performed case-insensitively.
     */
    CASELESS(nativeFlag(HyperscanNativeLoader.loadJni()::hsFlagCaseless)),

    /**
     * Matching a . will not exclude newlines.
     */
    DOTALL(nativeFlag(HyperscanNativeLoader.loadJni()::hsFlagDotall)),

    /**
     * ^ and $ anchors match any newlines in data.
     */
    MULTILINE(nativeFlag(HyperscanNativeLoader.loadJni()::hsFlagMultiline)),

    /**
     * Only one match will be generated by the expression per stream.
     */
    SINGLEMATCH(nativeFlag(HyperscanNativeLoader.loadJni()::hsFlagSinglematch)),

    /**
     * Allow expressions which can match against an empty string, such as .*.
     */
    ALLOWEMPTY(nativeFlag(HyperscanNativeLoader.loadJni()::hsFlagAllowempty)),

    /**
     * Treat this pattern as a sequence of UTF-8 characters.
     */
    UTF8(nativeFlag(HyperscanNativeLoader.loadJni()::hsFlagUtf8)),

    /**
     * Use Unicode properties for character classes.
     */
    UCP(nativeFlag(HyperscanNativeLoader.loadJni()::hsFlagUcp)),

    /**
     * compile pattern in prefiltering mode.
     */
    PREFILTER(nativeFlag(HyperscanNativeLoader.loadJni()::hsFlagPrefilter)),

    /**
     * Report the leftmost start of match offset when a match is found.
     */
    SOM_LEFTMOST(nativeFlag(HyperscanNativeLoader.loadJni()::hsFlagSomLeftmost)),

    /**
     * Parse the expression in logical combination syntax.
     */
    COMBINATION(nativeFlag(HyperscanNativeLoader.loadJni()::hsFlagCombination)),

    /**
     * Ignore match reporting for this expression. Used for the sub-expressions in logical combinations.
     */
    QUIET(nativeFlag(HyperscanNativeLoader.loadJni()::hsFlagQuiet));

    private final int bits;

    ExpressionFlag(int bitPosition) {
        this.bits = bitPosition;
    }

    /**
     * Get the significant bits for the flag
     * @return int containing the significant bit for the flag
     */
    public int getBits() {
        return bits;
    }

    private static int nativeFlag(IntSupplier supplier) {
        HyperscanNativeLoader.load();
        return supplier.getAsInt();
    }
}
